name = "MuTuner"
uuid = "206a444d-62d4-4bef-89ca-f2a4a27f2209"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "1.2.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Documenter = "0.27"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
