name = "MuTuner"
uuid = "206a444d-62d4-4bef-89ca-f2a4a27f2209"
authors = ["Benjamin Cohen-Stead <benwcs@gmail.com>"]
version = "0.1.5"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
DocumenterTools = "0.1"
Documenter = "0.27"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
